[project]
name = "rest-api-demo"
version = "0.1.0"
description = "This project is to demo a fastapi example that manages quotes with jwt auth"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.116.1",
    "uvicorn>=0.35.0",
]
