name: Deploy to AWS

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'terraform/**'
      - 'Dockerfile'

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: "us-east-2"
      ECR_REPO_NAME: quotes-api-demo-repo
      PROJECT_NAME: quotes-api-demo
      TF_STATE_BUCKET: "quotes-api-terraform-state"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.5

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Init
        working-directory: ./terraform/ecs
        env:
          TF_BACKEND_BUCKET: ${{ env.TF_STATE_BUCKET }}
          TF_BACKEND_REGION: ${{ env.AWS_REGION }}
        run: |
          terraform init \
            -backend-config="bucket=$TF_BACKEND_BUCKET" \
            -backend-config="region=$TF_BACKEND_REGION"

      - name: Terraform Apply
        working-directory: ./terraform/ecs
        env:
          TF_VAR_aws_region: ${{ env.AWS_REGION }}
        run: terraform apply -auto-approve
