name: Build and Push Docker Image

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: "us-east-2"
      ECR_REPO_NAME: quotes-api-demo-repo
      TF_STATE_BUCKET: "quotes-api-terraform-state"
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.5

      - name: Terraform Init (ECR)
        working-directory: ./terraform/ecr
        env:
          TF_BACKEND_BUCKET: ${{ env.TF_STATE_BUCKET }}
          TF_BACKEND_REGION: ${{ env.AWS_REGION }}
        run: |
          terraform init \
            -backend-config="bucket=$TF_BACKEND_BUCKET" \
            -backend-config="region=$TF_BACKEND_REGION"

      - name: Terraform Apply (ECR)
        working-directory: ./terraform/ecr
        env:
          TF_VAR_aws_region: ${{ env.AWS_REGION }}
        run: terraform apply -auto-approve

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push Docker image to ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          # Create a timestamp tag for versioning
          TIMESTAMP=$(date +%Y%m%d-%H%M%S)
          SHORT_SHA=$(git rev-parse --short HEAD)
          
          # Build the image
          docker build -t $ECR_REPO_NAME .
          
          # Tag with timestamp, commit SHA, and latest
          docker tag $ECR_REPO_NAME:latest $ECR_REGISTRY/$ECR_REPO_NAME:$TIMESTAMP-$SHORT_SHA
          docker tag $ECR_REPO_NAME:latest $ECR_REGISTRY/$ECR_REPO_NAME:latest
          
          # Push both tags
          docker push $ECR_REGISTRY/$ECR_REPO_NAME:$TIMESTAMP-$SHORT_SHA
          docker push $ECR_REGISTRY/$ECR_REPO_NAME:latest
          
          # Output the image tag for other workflows
          echo "IMAGE_TAG=$TIMESTAMP-$SHORT_SHA" >> $GITHUB_ENV
